# 
from debian:sid
MAINTAINER Metocean Solutions(Steve Fister)

run apt-get update 
run apt-get install -y \
   wget \
   curl 

#Install utilities

ADD VMware-Player-7.1.2-2780323.x86_64.bundle /VMware-Player-7.1.2-2780323.x86_64.bundle
RUN sh /VMware-Player-7.1.2-2780323.x86_64.bundle --console --eulas-agreed --required





