from debian:sid
# http://blog.tryolabs.com/2012/06/25/connecting-sql-server-database-python-under-ubuntu/

run apt-get update 
run apt-get install -y \
   wget \
   curl 
run apt-get install -y \
   unixodbc
run apt-get install -y \
   tdsodbc 
run apt-get update 
run apt-get install -y \
   build-essential
#run apt-get install -y \
#   gcc 
run apt-get install -y \
   python-pip 
run apt-get install -y \
   python-dev 
run apt-get install -y \
   freetds-dev

run pip install pymssql


