from debian:sid
# http://blog.tryolabs.com/2012/06/25/connecting-sql-server-database-python-under-ubuntu/

run apt-get update 
run apt-get install -y \
   wget \
   curl 
run apt-get install -y \
   unixodbc 
run apt-get install -y \
   unixodbc-dev \
   freetds-dev 
run apt-get install -y \
   tdsodbc 


